# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63b82ce5aa05d35079bffe8e7295d02809e782bbd82c492a7f50912a1db1464497499f1d6f968bb8cddf1aa5907e9ae1a53a47e94a0d2ea52a44362fab8aefbe

test:
  secret_key_base: 6ae2d28061dce6bf096060140e9514aa0dbad53ce81cd713fdffc75224483ca87aa719a9548fdf6aa3c31e4e210d820f83f27ce215b6e510b8f2ecb55039cfeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
